package de.mosst.labor.spring.boot;

import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.ResponseBody;

@Controller
public class MainController {
	
	@RequestMapping("/")
	@ResponseBody
	public String rootContext(){
		return "Start";
	}
	
	@RequestMapping("/hello")
	public String rootContext(Model model){
		model.addAttribute("german", "of executable JAR with JSPs generated by gradle!");
		return "hello-world";
	}

}
